
  query getVendorsByStore($vendorsByStoreInput: VendorsByStoreInput) {
    getVendorsByStore(vendorsByStoreInput: $vendorsByStoreInput) @context(provider: "vtex.instore-chk-graphql") {
      id
      name
      store
      user
      code
    }
  }
