#import "../fragments/customer.fragment.gql"

query GET_CUSTOMER {
	customer {
		...CustomerFields
		orders(first: 10) {
			edges {
				node {
					id
				}
			}
		}
	}
}

query GET_CUSTOMER_ORDERS($first: Int!, $after: String, $sortKey: OrderSortKeys, $reverse: Boolean) {
	customer {
		orders(first: $first, after: $after, sortKey: $sortKey, reverse: $reverse) {
			edges {
				node {
					...OrderFields
					lineItems(first: 50) {
						edges {
							node {
								...LineItemFields
							}
						}
					}
				}
				cursor
			}
			pageInfo {
				hasNextPage
				hasPreviousPage
			}
		}
	}
}

mutation CUSTOMER_UPDATE($input: CustomerUpdateInput!) {
	customerUpdate(input: $input) {
		customer {
			...CustomerFields
		}
		userErrors {
			code
			field
			message
		}
	}
}

mutation CUSTOMER_ADDRESS_CREATE($address: CustomerAddressInput!, $defaultAddress: Boolean) {
	customerAddressCreate(address: $address, defaultAddress: $defaultAddress) {
		customerAddress {
			...CustomerAddressFields
		}
		userErrors {
			code
			field
			message
		}
	}
}

mutation CUSTOMER_ADDRESS_UPDATE($addressId: ID!, $address: CustomerAddressInput, $defaultAddress: Boolean) {
	customerAddressUpdate(addressId: $addressId, address: $address, defaultAddress: $defaultAddress) {
		customerAddress {
			...CustomerAddressFields
		}
		userErrors {
			code
			field
			message
		}
	}
}

mutation CUSTOMER_ADDRESS_DELETE($addressId: ID!) {
	customerAddressDelete(addressId: $addressId) {
		deletedAddressId
		userErrors {
			code
			field
			message
		}
	}
}
